# Easy Cast du Multi Hub
# Toplevel Makefile allowing easy distribution ;)
#
# Jeroen Massar <jeroen@unfix.org>

# The name of the application
ECMH=ecmh
# The version of this release
ECMH_VERSION=2004.01.10
export ECMH_VERSION

# Change this if you want to install into another dirtree
# Required for eg the Debian Package builder
DESTDIR=

# Get the source dir, needed for eg debsrc
SOURCEDIR := $(shell pwd)

# Misc bins
RM=rm -f

# Paths
sbindir=/usr/sbin/
srcdir=src/

all:	${srcdir}
	$(MAKE) -C src all

install: all
	mkdir -p $(DESTDIR)${sbindir}
	cp src/$(ECMH) $(DESTDIR)${sbindir}

# Clean all the output files etc
distclean: clean

clean:
	$(MAKE) -C src clean
	# Also clean some leftovers generated by debian
	rm -rf build-stamp configure-stamp debian/ecmh/

# Generate Distribution files
dist:	tar bz2 deb debsrc rpm rpmsrc

# tar.gz
tar:	clean
	-${RM} ../ecmh_${ECMH_VERSION}.tar.gz
	tar -zclof ../ecmh_${ECMH_VERSION}.tar.gz *

# tar.bz2
bz2:	clean
	-${RM} ../ecmh_${ECMH_VERSION}.tar.bz2
	tar -jclof ../ecmh_${ECMH_VERSION}.tar.bz2 *

# .deb
deb:	clean
	debian/rules binary
	THIS=`pwd`
	${MAKE} clean

# Source .deb
debsrc: clean
	cd ..; dpkg-source -b ${SOURCEDIR}; cd ${SOURCEDIR}

# RPM
rpm:	clean
	# TODO ;)
	${MAKE} clean

rpmsrc:	clean
	# TODO ;)

# Mark targets as phony
.PHONY : all install clean dist tar bz2 deb debsrc rpm rpmsrc

