# /**************************************
#  ecmh - Easy Cast du Multi Hub
#  by Jeroen Massar <jeroen@massar.ch>
# **************************************/
#
# Tools Makefile
#

all:	mtrace6

mtrace6: mtrace6/
	$(MAKE) -C mtrace6 all

clean:
	$(MAKE) -C mtrace6 clean

# Mark targets as phony
.PHONY : all clean mtrace6

